name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_FE }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          sudo docker stop frontend || true
          sudo docker rm frontend || true
          sudo docker run -d \
            --name frontend \
            -p 80:80 \
            -v /etc/ssl/certs:/etc/ssl/certs:ro \
            ${{ secrets.DOCKER_USERNAME }}/frontend:latest